import { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'EN' | 'FR' | 'ES';

export const translations = {
  EN: {
    nav: {
      about: 'About',
      properties: 'Properties',
      services: 'Services',
      contact: 'Contact',
      enquire: 'Enquire',
      home: 'Home',
    },
    hero: {
      location: 'Marbella · Costa del Sol · Morocco',
      headline1: 'Where Luxury',
      headline2: 'Meets the',
      headlineItalic: 'Mediterranean',
      sub: "Exclusive properties on Spain's most prestigious coastline and Morocco's most storied medinas. Boutique service. Absolute discretion.",
      cta1: 'Explore Properties',
      cta2: 'Private Consultation',
    },
    stats: [
      { number: '€1.6M+', label: 'Starting Price' },
      { number: '2', label: 'Countries' },
      { number: '3', label: 'Languages Spoken' },
      { number: '100%', label: 'Boutique Service' },
    ],
    about: {
      eyebrow: 'Our Story',
      heading: 'A Boutique Firm\nBuilt on Passion',
      quote: '"Excellence is not a service feature —\nit is our founding principle."',
      p1: "Riffinity Real Estate is a luxury property firm specialising in Marbella's most coveted addresses — from the Golden Mile to Puerto Banús — and now, the extraordinary heritage estates of Marrakech. Founded on the belief that every client deserves a truly extraordinary experience, we combine deep market knowledge with an uncompromisingly personal approach.",
      p2: 'Our team operates fluently in English, French, and Spanish, serving an international clientele who demand discretion, insight, and flawless execution at every stage of their journey.',
      cta: 'Discover Our Services',
      badge1: '12+',
      badge2: 'Years in Luxury\nReal Estate',
    },
    services: {
      eyebrow: 'What We Offer',
      heading: 'Three Pillars of\nExceptional Service',
      sub: "From acquisition to luxury concierge, Riffinity offers a complete ecosystem of services tailored to the world's most discerning buyers, sellers, and guests.",
      learnMore: 'Learn more',
      items: [
        {
          num: '01',
          title: 'Property Sales & Acquisitions',
          body: 'Expert guidance on buying and selling luxury villas, apartments, and estates in Marbella and across the Costa del Sol. Access to exclusive off-market listings unavailable to the general market.',
        },
        {
          num: '02',
          title: 'Short-Term Luxury Rentals',
          body: 'Curated holiday rentals in hand-selected properties — from beachfront villas 200m from the sea to hillside retreats with panoramic Mediterranean views, and heritage riads in the Marrakech Medina.',
        },
        {
          num: '03',
          title: 'Luxury Concierge',
          body: "Premium lifestyle services for our clients — from private transportation and yacht charters to restaurant reservations and exclusive event access in Marbella, Puerto Banús, and Marrakech.",
        },
      ],
    },
    properties: {
      eyebrow: 'For Sale',
      heading: 'Featured Properties',
      viewAll: 'View All Listings',
      viewDetails: 'View Details',
      details: 'Details',
      beds: 'Beds',
      baths: 'Baths',
      prev: 'Prev',
      next: 'Next',
    },
    banner: {
      eyebrow: 'A Private World',
      heading: 'Every Property Tells',
      headingItalic: 'an Extraordinary Story',
      cta: 'Discover the Collection',
    },
    contact: {
      eyebrow: 'Private Consultation',
      heading1: 'Begin Your',
      headingItalic: 'Riffinity Journey',
      sub: 'Whether you are buying, selling, or simply exploring possibilities, our team is at your service. Every enquiry is handled with absolute discretion.',
      email: 'Email',
      instagram: 'Instagram',
      offices: 'Offices',
      officesValue: 'Marbella, Spain · Marrakech, Morocco',
      firstName: 'First Name',
      lastName: 'Last Name',
      emailLabel: 'Email Address',
      phone: 'Phone (optional)',
      interest: 'Interest',
      message: 'Message',
      send: 'Send Enquiry',
      privacy: 'Your information is kept strictly confidential and will never be shared with third parties.',
      interests: [
        { value: 'buy', label: 'Buying a Property' },
        { value: 'sell', label: 'Selling a Property' },
        { value: 'rental', label: 'Short-Term Rental' },
        { value: 'concierge', label: 'Luxury Concierge' },
        { value: 'other', label: 'General Enquiry' },
      ],
      successTitle: 'Message Received',
      successSub: "We'll be in touch within 24 hours.",
    },
    footer: {
      tagline: "Luxury real estate and lifestyle services in Marbella, Costa del Sol, and Morocco.",
      propertiesHeading: 'Properties',
      servicesHeading: 'Services',
      contactHeading: 'Contact',
      allListings: 'All Listings',
      marbellaVillas: 'Marbella Villas',
      moroccoRiads: 'Morocco Riads',
      holidayRentals: 'Holiday Rentals',
      sales: 'Property Sales',
      acquisitions: 'Acquisitions',
      concierge: 'Luxury Concierge',
      consultation: 'Private Consultation',
      rights: '© 2026 Riffinity Real Estate. All rights reserved.',
      privacy: 'Privacy Policy',
      legal: 'Legal Notice',
      cookie: 'Cookie Policy',
    },
    listing: {
      title: 'Featured Properties',
      eyebrow: 'Exclusive Collection',
      sub: "Discover our curated selection of luxury properties in Marbella's most prestigious locations and Morocco's most extraordinary destinations.",
      allLocations: 'All Locations',
      propertiesCount: 'properties',
      askingPrice: 'Asking Price',
      viewFull: 'View Full Details',
      enquireNow: 'Enquire Now',
      viewDetails: 'View Details',
      noResults: 'No properties match your current filters.',
      clearFilters: 'Clear Filters',
    },
    detail: {
      back: 'Properties',
      forSale: 'For Sale',
      bedrooms: 'Bedrooms',
      bathrooms: 'Bathrooms',
      builtArea: 'Built Area',
      garage: 'Garage',
      yearBuilt: 'Year Built',
      about: 'About This Property',
      features: 'Key Features',
      location: 'Location',
      askingPrice: 'Asking Price',
      requestViewing: 'Request Viewing',
      contactAgent: 'Contact Agent',
      trilingual: 'Trilingual team (EN/FR/ES)',
      discretion: 'Absolute discretion guaranteed',
      privateViewing: 'Private viewings available',
      yourAgent: 'Your Agent',
      agentTitle: 'Luxury Property Specialists',
      enquire: 'Enquire',
      youMayAlsoLike: 'You May Also Like',
      similarProperties: 'Similar Properties',
      requestViewingModal: 'Request Viewing',
      sendRequest: 'Send Request',
      messagePlaceholder: 'Message (optional)',
      marbellaDesc: "Marbella, Costa del Sol — one of Europe's most prestigious coastal destinations.",
      moroccoDesc: "Marrakech — Morocco's cultural capital, where centuries of history meet extraordinary luxury.",
      spain: 'Spain',
      morocco: 'Morocco',
    },
  },

  FR: {
    nav: {
      about: 'À Propos',
      properties: 'Propriétés',
      services: 'Services',
      contact: 'Contact',
      enquire: 'Renseignements',
      home: 'Accueil',
    },
    hero: {
      location: 'Marbella · Costa del Sol · Maroc',
      headline1: 'Là où le Luxe',
      headline2: 'Rencontre la',
      headlineItalic: 'Méditerranée',
      sub: "Des propriétés exclusives sur le littoral le plus prestigieux d'Espagne et dans les médinas les plus emblématiques du Maroc. Service boutique. Discrétion absolue.",
      cta1: 'Explorer les Propriétés',
      cta2: 'Consultation Privée',
    },
    stats: [
      { number: '€1,6M+', label: 'Prix de Départ' },
      { number: '2', label: 'Pays' },
      { number: '3', label: 'Langues Parlées' },
      { number: '100%', label: 'Service Boutique' },
    ],
    about: {
      eyebrow: 'Notre Histoire',
      heading: 'Une Agence Boutique\nFondée sur la Passion',
      quote: '"L\'excellence n\'est pas un service — c\'est notre principe fondateur."',
      p1: "Riffinity Real Estate est une agence immobilière de luxe spécialisée dans les adresses les plus recherchées de Marbella — du Golden Mile à Puerto Banús — et désormais, dans les extraordinaires demeures patrimoniales de Marrakech. Fondée sur la conviction que chaque client mérite une expérience véritablement exceptionnelle, nous allions une connaissance approfondie du marché à une approche résolument personnalisée.",
      p2: "Notre équipe maîtrise parfaitement l'anglais, le français et l'espagnol, au service d'une clientèle internationale qui exige discrétion, perspicacité et exécution irréprochable à chaque étape de leur parcours.",
      cta: 'Découvrir Nos Services',
      badge1: '12+',
      badge2: 'Ans dans\nl\'Immobilier de Luxe',
    },
    services: {
      eyebrow: 'Ce que Nous Offrons',
      heading: 'Trois Piliers d\'un\nService d\'Exception',
      sub: "De l'acquisition au concierge de luxe, Riffinity propose un écosystème complet de services sur mesure pour les acheteurs, vendeurs et résidents les plus exigeants au monde.",
      learnMore: 'En savoir plus',
      items: [
        {
          num: '01',
          title: 'Vente & Acquisition Immobilière',
          body: "Accompagnement expert pour l'achat et la vente de villas, appartements et domaines de luxe à Marbella et sur la Costa del Sol. Accès à des biens exclusifs hors marché.",
        },
        {
          num: '02',
          title: 'Locations de Luxe de Courte Durée',
          body: "Locations de vacances triées sur le volet — des villas en bord de mer à 200 m de la plage aux retraites en montagne avec vue panoramique sur la Méditerranée, et des riads patrimoniaux dans la Médina de Marrakech.",
        },
        {
          num: '03',
          title: 'Conciergerie de Luxe',
          body: "Services de style de vie premium — transport privé, charters de yachts, réservations dans les meilleurs restaurants et accès à des événements exclusifs à Marbella, Puerto Banús et Marrakech.",
        },
      ],
    },
    properties: {
      eyebrow: 'À Vendre',
      heading: 'Propriétés en Vedette',
      viewAll: 'Voir Toutes les Annonces',
      viewDetails: 'Voir les Détails',
      details: 'Détails',
      beds: 'Chambres',
      baths: 'SDB',
      prev: 'Préc.',
      next: 'Suiv.',
    },
    banner: {
      eyebrow: 'Un Monde Privé',
      heading: 'Chaque Propriété Raconte',
      headingItalic: 'une Histoire Extraordinaire',
      cta: 'Découvrir la Collection',
    },
    contact: {
      eyebrow: 'Consultation Privée',
      heading1: 'Commencez Votre',
      headingItalic: 'Voyage Riffinity',
      sub: "Que vous souhaitiez acheter, vendre ou simplement explorer les possibilités, notre équipe est à votre service. Chaque demande est traitée avec une discrétion absolue.",
      email: 'Email',
      instagram: 'Instagram',
      offices: 'Bureaux',
      officesValue: 'Marbella, Espagne · Marrakech, Maroc',
      firstName: 'Prénom',
      lastName: 'Nom de Famille',
      emailLabel: 'Adresse Email',
      phone: 'Téléphone (optionnel)',
      interest: 'Intérêt',
      message: 'Message',
      send: 'Envoyer la Demande',
      privacy: 'Vos informations sont strictement confidentielles et ne seront jamais partagées avec des tiers.',
      interests: [
        { value: 'buy', label: "Acheter une Propriété" },
        { value: 'sell', label: 'Vendre une Propriété' },
        { value: 'rental', label: 'Location Courte Durée' },
        { value: 'concierge', label: 'Conciergerie de Luxe' },
        { value: 'other', label: 'Renseignement Général' },
      ],
      successTitle: 'Message Reçu',
      successSub: 'Nous vous contacterons dans les 24 heures.',
    },
    footer: {
      tagline: "Services immobiliers de luxe et de style de vie à Marbella, Costa del Sol et Maroc.",
      propertiesHeading: 'Propriétés',
      servicesHeading: 'Services',
      contactHeading: 'Contact',
      allListings: 'Toutes les Annonces',
      marbellaVillas: 'Villas à Marbella',
      moroccoRiads: 'Riads au Maroc',
      holidayRentals: 'Locations de Vacances',
      sales: 'Vente Immobilière',
      acquisitions: 'Acquisitions',
      concierge: 'Conciergerie de Luxe',
      consultation: 'Consultation Privée',
      rights: '© 2026 Riffinity Real Estate. Tous droits réservés.',
      privacy: 'Politique de Confidentialité',
      legal: 'Mentions Légales',
      cookie: 'Politique de Cookies',
    },
    listing: {
      title: 'Propriétés en Vedette',
      eyebrow: 'Collection Exclusive',
      sub: "Découvrez notre sélection de propriétés de luxe dans les emplacements les plus prestigieux de Marbella et les destinations les plus extraordinaires du Maroc.",
      allLocations: 'Tous les Emplacements',
      propertiesCount: 'propriétés',
      askingPrice: 'Prix Demandé',
      viewFull: 'Voir tous les Détails',
      enquireNow: 'Demander Maintenant',
      viewDetails: 'Voir les Détails',
      noResults: 'Aucune propriété ne correspond à vos filtres.',
      clearFilters: 'Effacer les Filtres',
    },
    detail: {
      back: 'Propriétés',
      forSale: 'À Vendre',
      bedrooms: 'Chambres',
      bathrooms: 'Salles de Bain',
      builtArea: 'Surface Bâtie',
      garage: 'Garage',
      yearBuilt: 'Année de Construction',
      about: 'À Propos de cette Propriété',
      features: 'Caractéristiques Clés',
      location: 'Emplacement',
      askingPrice: 'Prix Demandé',
      requestViewing: 'Demander une Visite',
      contactAgent: "Contacter l'Agent",
      trilingual: 'Équipe trilingue (EN/FR/ES)',
      discretion: 'Discrétion absolue garantie',
      privateViewing: 'Visites privées disponibles',
      yourAgent: 'Votre Agent',
      agentTitle: 'Spécialistes en Immobilier de Luxe',
      enquire: 'Renseignements',
      youMayAlsoLike: 'Vous Aimerez Peut-être',
      similarProperties: 'Propriétés Similaires',
      requestViewingModal: 'Demander une Visite',
      sendRequest: 'Envoyer la Demande',
      messagePlaceholder: 'Message (optionnel)',
      marbellaDesc: "Marbella, Costa del Sol — l'une des destinations côtières les plus prestigieuses d'Europe.",
      moroccoDesc: "Marrakech — capitale culturelle du Maroc, où des siècles d'histoire rencontrent un luxe extraordinaire.",
      spain: 'Espagne',
      morocco: 'Maroc',
    },
  },

  ES: {
    nav: {
      about: 'Nosotros',
      properties: 'Propiedades',
      services: 'Servicios',
      contact: 'Contacto',
      enquire: 'Consultar',
      home: 'Inicio',
    },
    hero: {
      location: 'Marbella · Costa del Sol · Marruecos',
      headline1: 'Donde el Lujo',
      headline2: 'Se Encuentra con el',
      headlineItalic: 'Mediterráneo',
      sub: "Propiedades exclusivas en el litoral más prestigioso de España y en las medinas más fascinantes de Marruecos. Servicio boutique. Discreción absoluta.",
      cta1: 'Explorar Propiedades',
      cta2: 'Consulta Privada',
    },
    stats: [
      { number: '€1,6M+', label: 'Precio Inicial' },
      { number: '2', label: 'Países' },
      { number: '3', label: 'Idiomas Hablados' },
      { number: '100%', label: 'Servicio Boutique' },
    ],
    about: {
      eyebrow: 'Nuestra Historia',
      heading: 'Una Agencia Boutique\nFundada en la Pasión',
      quote: '"La excelencia no es un servicio — es nuestro principio fundador."',
      p1: "Riffinity Real Estate es una inmobiliaria de lujo especializada en las direcciones más codiciadas de Marbella — desde el Golden Mile hasta Puerto Banús — y ahora también en las extraordinarias propiedades históricas de Marrakech. Fundada en la convicción de que cada cliente merece una experiencia verdaderamente extraordinaria, combinamos un profundo conocimiento del mercado con un enfoque genuinamente personalizado.",
      p2: "Nuestro equipo opera con fluidez en inglés, francés y español, al servicio de una clientela internacional que exige discreción, perspicacia y ejecución impecable en cada etapa de su recorrido.",
      cta: 'Descubrir Nuestros Servicios',
      badge1: '12+',
      badge2: 'Años en Bienes\nRaíces de Lujo',
    },
    services: {
      eyebrow: 'Lo que Ofrecemos',
      heading: 'Tres Pilares de un\nServicio Excepcional',
      sub: "Desde la adquisición hasta la conserjería de lujo, Riffinity ofrece un ecosistema completo de servicios adaptado a los compradores, vendedores e inquilinos más exigentes del mundo.",
      learnMore: 'Saber más',
      items: [
        {
          num: '01',
          title: 'Venta y Adquisición de Propiedades',
          body: 'Asesoramiento experto en la compra y venta de villas de lujo, apartamentos y fincas en Marbella y en toda la Costa del Sol. Acceso a listados exclusivos fuera del mercado.',
        },
        {
          num: '02',
          title: 'Alquileres de Lujo a Corto Plazo',
          body: 'Alquileres vacacionales cuidadosamente seleccionados — desde villas en primera línea de playa a 200 m del mar hasta retiros en la sierra con vistas panorámicas al Mediterráneo y riads históricos en la Medina de Marrakech.',
        },
        {
          num: '03',
          title: 'Conserjería de Lujo',
          body: "Servicios de estilo de vida premium — transporte privado, chárter de yates, reservas en restaurantes exclusivos y acceso a eventos de élite en Marbella, Puerto Banús y Marrakech.",
        },
      ],
    },
    properties: {
      eyebrow: 'En Venta',
      heading: 'Propiedades Destacadas',
      viewAll: 'Ver Todos los Listados',
      viewDetails: 'Ver Detalles',
      details: 'Detalles',
      beds: 'Habs.',
      baths: 'Baños',
      prev: 'Ant.',
      next: 'Sig.',
    },
    banner: {
      eyebrow: 'Un Mundo Privado',
      heading: 'Cada Propiedad Cuenta',
      headingItalic: 'una Historia Extraordinaria',
      cta: 'Descubrir la Colección',
    },
    contact: {
      eyebrow: 'Consulta Privada',
      heading1: 'Comience su',
      headingItalic: 'Viaje Riffinity',
      sub: 'Ya sea que desee comprar, vender o simplemente explorar posibilidades, nuestro equipo está a su disposición. Cada consulta se gestiona con absoluta discreción.',
      email: 'Correo Electrónico',
      instagram: 'Instagram',
      offices: 'Oficinas',
      officesValue: 'Marbella, España · Marrakech, Marruecos',
      firstName: 'Nombre',
      lastName: 'Apellidos',
      emailLabel: 'Dirección de Email',
      phone: 'Teléfono (opcional)',
      interest: 'Interés',
      message: 'Mensaje',
      send: 'Enviar Consulta',
      privacy: 'Su información es estrictamente confidencial y nunca será compartida con terceros.',
      interests: [
        { value: 'buy', label: 'Comprar una Propiedad' },
        { value: 'sell', label: 'Vender una Propiedad' },
        { value: 'rental', label: 'Alquiler a Corto Plazo' },
        { value: 'concierge', label: 'Conserjería de Lujo' },
        { value: 'other', label: 'Consulta General' },
      ],
      successTitle: 'Mensaje Recibido',
      successSub: 'Nos pondremos en contacto en un plazo de 24 horas.',
    },
    footer: {
      tagline: "Servicios inmobiliarios de lujo y estilo de vida en Marbella, Costa del Sol y Marruecos.",
      propertiesHeading: 'Propiedades',
      servicesHeading: 'Servicios',
      contactHeading: 'Contacto',
      allListings: 'Todos los Listados',
      marbellaVillas: 'Villas en Marbella',
      moroccoRiads: 'Riads en Marruecos',
      holidayRentals: 'Alquileres Vacacionales',
      sales: 'Venta Inmobiliaria',
      acquisitions: 'Adquisiciones',
      concierge: 'Conserjería de Lujo',
      consultation: 'Consulta Privada',
      rights: '© 2026 Riffinity Real Estate. Todos los derechos reservados.',
      privacy: 'Política de Privacidad',
      legal: 'Aviso Legal',
      cookie: 'Política de Cookies',
    },
    listing: {
      title: 'Propiedades Destacadas',
      eyebrow: 'Colección Exclusiva',
      sub: "Descubra nuestra selección de propiedades de lujo en las ubicaciones más prestigiosas de Marbella y los destinos más extraordinarios de Marruecos.",
      allLocations: 'Todas las Ubicaciones',
      propertiesCount: 'propiedades',
      askingPrice: 'Precio',
      viewFull: 'Ver Detalles Completos',
      enquireNow: 'Consultar Ahora',
      viewDetails: 'Ver Detalles',
      noResults: 'Ninguna propiedad coincide con sus filtros.',
      clearFilters: 'Borrar Filtros',
    },
    detail: {
      back: 'Propiedades',
      forSale: 'En Venta',
      bedrooms: 'Dormitorios',
      bathrooms: 'Baños',
      builtArea: 'Superficie Construida',
      garage: 'Garaje',
      yearBuilt: 'Año de Construcción',
      about: 'Sobre esta Propiedad',
      features: 'Características Principales',
      location: 'Ubicación',
      askingPrice: 'Precio',
      requestViewing: 'Solicitar Visita',
      contactAgent: 'Contactar Agente',
      trilingual: 'Equipo trilingüe (EN/FR/ES)',
      discretion: 'Discreción absoluta garantizada',
      privateViewing: 'Visitas privadas disponibles',
      yourAgent: 'Su Agente',
      agentTitle: 'Especialistas en Inmobiliaria de Lujo',
      enquire: 'Consultar',
      youMayAlsoLike: 'También le Puede Interesar',
      similarProperties: 'Propiedades Similares',
      requestViewingModal: 'Solicitar Visita',
      sendRequest: 'Enviar Solicitud',
      messagePlaceholder: 'Mensaje (opcional)',
      marbellaDesc: "Marbella, Costa del Sol — uno de los destinos costeros más prestigiosos de Europa.",
      moroccoDesc: "Marrakech — capital cultural de Marruecos, donde siglos de historia se encuentran con un lujo extraordinario.",
      spain: 'España',
      morocco: 'Marruecos',
    },
  },
} as const;

export type Translations = typeof translations.EN;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'EN',
  setLang: () => {},
  t: translations.EN,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('ES');
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}